# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  fileSystems."/" = {
    device = "/dev/disk/by-uuid/24e28253-6896-45e8-a585-e3cb061e3e8a";
    fsType = "btrfs";
    options = [
      "subvol=root"
      "compress=zstd"
    ];
  };

  fileSystems."/home/aimi" = {
    device = "/dev/disk/by-uuid/24e28253-6896-45e8-a585-e3cb061e3e8a";
    fsType = "btrfs";
    options = [ "subvol=home_aimi" ];
  };

  fileSystems."/home/aimi/workspace" = {
    device = "/dev/disk/by-uuid/24e28253-6896-45e8-a585-e3cb061e3e8a";
    fsType = "btrfs";
    options = [ "subvol=home_aimi_workspace" ];
  };

  fileSystems."/home/aimi/.cache" = {
    device = "/dev/disk/by-uuid/24e28253-6896-45e8-a585-e3cb061e3e8a";
    fsType = "btrfs";
    options = [ "subvol=home_aimi_cache" ];
  };

  fileSystems."/home/aimi/games" = {
    device = "/dev/disk/by-uuid/24e28253-6896-45e8-a585-e3cb061e3e8a";
    fsType = "btrfs";
    options = [ "subvol=home_aimi_games" ];
  };

  fileSystems."/home/aimi/torrents" = {
    device = "/dev/disk/by-uuid/24e28253-6896-45e8-a585-e3cb061e3e8a";
    fsType = "btrfs";
    options = [
      "subvol=home_aimi_torrents"
    ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/8222-131B";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  swapDevices = [ ];

}
